// Generated by CoffeeScript 1.4.0
(function() {
  var Backbone, CollectionExposerHttp, helpers, _;

  helpers = require('helpers');

  Backbone = require('backbone4000');

  _ = require('underscore');

  CollectionExposerHttp = exports.CollectionExposerHttp = Backbone.Model.extend4000({
    initialize: function() {
      var app, c, callbackToRes, name, path,
        _this = this;
      path = this.get('path');
      app = this.get('app');
      c = this.get('collection');
      name = c.get('name');
      callbackToRes = function(res) {
        return function(err, data) {
          console.log('res', err, data);
          return res.end(JSON.stringify({
            err: err,
            data: data
          }));
        };
      };
      app.post(helpers.makePath(path, name, 'create'), function(req, res) {
        return c.create(req.body.data, callbackToRes(res));
      });
      app.post(helpers.makePath(path, name, 'remove'), function(req, res) {
        return c.remove(req.body.pattern, callbackToRes(res));
      });
      app.post(helpers.makePath(path, name, 'update'), function(req, res) {
        return c.update(req.body.pattern, req.body.data, callbackToRes(res));
      });
      app.post(helpers.makePath(path, name, 'find'), function(req, res) {
        var reslist;
        reslist = [];
        return c.find(req.body.pattern, req.body.limits, function(err, data) {
          if (data) {
            return reslist.push(data);
          } else {
            return res.end(JSON.stringify(reslist));
          }
        });
      });
      app.post(helpers.makePath(path, name, 'findOne'), function(req, res) {
        return c.findModel(req.body.pattern, function(err, model) {
          return res.end(JSON.stringify({
            err: err,
            data: model.attributes
          }));
        });
      });
      return app.post(helpers.makePath(path, name, 'call'), function(req, res) {
        return c.fcall(req.body["function"], req.body.args || [], req.body.pattern, void 0, function(err, data) {
          return res.end(JSON.stringify({
            err: err,
            data: data
          }));
        });
      });
    }
  });

}).call(this);
